site_name: 'MNX.io Docs'
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'images/logo.png'

nav:
    - Home: index.md
    - CloudAPI: /cloudapi/index.html
    - Security: https://mnx.io/security

